### ISSUE TITLE
apps is unusable with QGnome-platform

### ISSUE THREAD

**Issue by sekalengrengginang** [flathub/org.kde.plasmatube#1]
Because QGNOME-platform this apps is unusable on GNOME desktop 
![image](https://user-images.githubusercontent.com/49896401/221397289-cd699d14-47f2-4019-b0a3-930d6768ad2c.png)

**Comment by JBBgameich** [comment]
I actually think it's unusable due to a lack of integration, it looks like it doesn't have an icon theme and a style set, so uses reeeallly basic fallbacks.

**Comment by JBBgameich** [comment]
Looks like a custom fallback has been set upstream, but that commit is not yet part of a release: https://invent.kde.org/multimedia/plasmatube/-/commit/3c9be95050b17307ad6a9efa6ea7b526d8c1b4dd

**Comment by Newbytee** [comment]
This seems to have been fixed now.
