### ISSUE TITLE
Video playback doesnt deactivate KDE screen timeout

### ISSUE THREAD

**Issue by firefoxlover** [flathub/org.kde.plasmatube#3]
on firefox playing a video disables the screen from turning off automatically. 

This does not happen on Plasmatube as well as on Falkon.

Version: 23.04.0 Flathub

**Comment by JBBgameich** [comment]
Pretty sure this is just not implemented, not a flatpak issue

**Comment by redstrate** [comment]
This is now implemented in https://invent.kde.org/multimedia/plasmatube/-/merge_requests/57 and will show up in the 23.12 release.

**Comment by tsdgeos** [comment]
FWIW we're not having a 23.12 release https://community.kde.org/Schedules/February_2024_MegaRelease

**Comment by Justinzobel** [comment]
It can potentially be cherry-picked into a 23.08.x release then.

**Comment by redstrate** [comment]
> FWIW we're not having a 23.12 release https://community.kde.org/Schedules/February_2024_MegaRelease

Oops, right :D my bad, I need to stop saying 23.12

> It can potentially be cherry-picked into a 23.08.x release then.

Yeah maybe, there's a few other things we can cherry-pick too
